const CABINS = [
  {
    id: "capsula-uno",
    image: "img/capsula-uno.png",
    brand: "Capsula",
    model: "UNO",
    price: 803167,
    capacity: 1,
    soundproof: "39 дБ",
    soundproofVal: 39,
    dimensions: "—",
    warranty: "2 года каркас / 1 год прочее",
    warrantyYears: 2,
    delivery: "60 кал. дней",
    furniture: "Стул, стол, подножка",
    power: "1× розетка 220В, USB, USB-C, беспроводная зарядка",
    features: [
      "Корпус с тонированной стеклянной дверью",
      "Микроконтроллер с управлением режимами",
      "Фронтальные + верхний светильники",
      "Индикатор занятости фронтальный и нижний",
      "Крючки, магнитные аксессуары",
      "Светло-серый войлок + шпон",
      "Рассрочка на 6 мес."
    ]
  },
  {
    id: "capsula-duo",
    image: "img/capsula-duo.png",
    brand: "Capsula",
    model: "DUO",
    price: 1418250,
    capacity: 2,
    soundproof: "39 дБ",
    soundproofVal: 39,
    dimensions: "—",
    warranty: "2 года каркас / 1 год прочее",
    warrantyYears: 2,
    delivery: "60 кал. дней",
    furniture: "2 дивана, стол-трансформер",
    power: "2× розетки 220В, 2× USB, 2× USB-C, 2× беспроводные зарядки",
    features: [
      "Тонированное стекло двери",
      "Микроконтроллер расширенный",
      "Индикаторы занятости фронтальные и нижние",
      "Верхний светильник",
      "2 пары крючков, магнитные аксессуары",
      "Войлок + шпон",
      "Рассрочка на 6 мес."
    ]
  },
  {
    id: "capsula-quatro",
    image: "img/capsula-quatro.png",
    brand: "Capsula",
    model: "QUATRO",
    price: 1753750,
    capacity: 4,
    soundproof: "39 дБ",
    soundproofVal: 39,
    dimensions: "—",
    warranty: "2 года каркас / 1 год прочее",
    warrantyYears: 2,
    delivery: "90 кал. дней",
    furniture: "2 дивана, стол",
    power: "3× розетки 220В, 2× USB, 2× USB-C, 2× беспроводные зарядки",
    features: [
      "Тонированное стекло двери",
      "Микроконтроллер расширенный",
      "Индикаторы занятости фронтальные и нижние",
      "Верхние светильники",
      "2 пары крючков, магнитные аксессуары",
      "Войлок + шпон",
      "Рассрочка на 6 мес."
    ]
  },
  {
    id: "qubius-one",
    image: "img/qubius-one.png",
    brand: "Qubius",
    model: "One",
    price: 923540,
    capacity: 1,
    soundproof: "≥32 дБ",
    soundproofVal: 32,
    dimensions: "—",
    warranty: "5 лет каркас / 2 года прочее",
    warrantyYears: 5,
    delivery: "45–60 раб. дней",
    furniture: "Стол (стул — опция)",
    power: "Розетка 220В, USB-A, USB-C",
    features: [
      "Внешняя отделка HPL на выбор из каталога",
      "Задняя стенка: триплекс 9–9,5 мм",
      "Диммируемый LED-светильник",
      "Микроконтроллер",
      "Доп. оснащение (платно): Qi-зарядка, эргостул, камера 180°"
    ]
  },
  {
    id: "qubius-team",
    image: "img/qubius-team.png",
    brand: "Qubius",
    model: "Team (TWO)",
    price: 1549400,
    capacity: 4,
    soundproof: "≥32 дБ",
    soundproofVal: 32,
    dimensions: "—",
    warranty: "5 лет каркас / 2 года прочее",
    warrantyYears: 5,
    delivery: "45–60 раб. дней",
    furniture: "2 дивана, стол",
    power: "2× розетки 220В, USB-A, USB-C",
    features: [
      "HPL-отделка на выбор",
      "Триплекс 9–9,5 мм",
      "Вентиляция до 1300 м³/час",
      "Датчик движения 360°",
      "Диммируемый LED 24 Вт + потолочные 40 Вт"
    ]
  },
  {
    id: "qubius-team-plus",
    image: "img/qubius-team-plus.png",
    brand: "Qubius",
    model: "Team+ (TEAM)",
    price: 1793400,
    capacity: 4,
    soundproof: "≥32 дБ",
    soundproofVal: 32,
    dimensions: "—",
    warranty: "5 лет каркас / 2 года прочее",
    warrantyYears: 5,
    delivery: "45–60 раб. дней",
    furniture: "2 дивана, стол",
    power: "2× розетки 220В, USB-A, USB-C",
    features: [
      "HPL-отделка премиум",
      "Триплекс 9–9,5 мм",
      "Вентиляция до 2600 м³/час (вдвое мощнее Team)",
      "Датчик движения 360°",
      "Диммируемый LED 24 Вт + потолочные 40 Вт",
      "Рассрочка на 6 мес."
    ]
  },
  {
    id: "lwoop-one-sky",
    image: "img/lwoop-one-sky.png",
    brand: "LWOOP",
    model: "ONE sky",
    price: 708750,
    capacity: 1,
    soundproof: ">32 дБ",
    soundproofVal: 32,
    dimensions: "1080×1000×2326h",
    warranty: "7 лет",
    warrantyYears: 7,
    delivery: "50 раб. дней",
    furniture: "Эргономичный стол HPL, барный стул с регулировкой",
    power: "Силовая розетка + USB + USB-C",
    features: [
      "Сталь + авиационный алюминий снаружи",
      "Фетр 10 мм + акустическая ткань внутри",
      "Ковролин",
      "Бесшумная вентиляция 91 м³, смена воздуха 16 сек",
      "Закалённое стекло 10 мм, магнитный замок",
      "Мобильность",
      "Вес 265 кг"
    ]
  },
  {
    id: "lwoop-onework-sky",
    image: "img/lwoop-onework-sky.png",
    brand: "LWOOP",
    model: "ONE WORK sky",
    price: 834375,
    capacity: 1,
    soundproof: ">32 дБ",
    soundproofVal: 32,
    dimensions: "1600×1375×2326h",
    warranty: "7 лет",
    warrantyYears: 7,
    delivery: "50 раб. дней",
    furniture: "Эргостол HPL, кресло",
    power: "Силовая розетка + USB + USB-C",
    features: [
      "Сталь + авиационный алюминий",
      "Фетр 10 мм + акустическая ткань",
      "Вентиляция 110 м³, смена воздуха 16 сек",
      "Закалённое стекло 10 мм, магнитный замок",
      "Мобильность, вес 409 кг"
    ]
  },
  {
    id: "lwoop-double-sky",
    image: "img/lwoop-double-sky.png",
    brand: "LWOOP",
    model: "DOUBLE sky",
    price: 1143178,
    capacity: 2,
    soundproof: ">32 дБ",
    soundproofVal: 32,
    dimensions: "2300×966×2364h",
    warranty: "7 лет",
    warrantyYears: 7,
    delivery: "50 раб. дней",
    furniture: "2 одноместных дивана, стол",
    power: "Силовая розетка + USB + USB-C",
    features: [
      "Сталь + авиационный алюминий",
      "Фетр 10 мм + акустическая ткань",
      "Вентиляция 110 м³",
      "Триплекс 10 мм с ламинацией (опция) или фетр",
      "Мобильность, вес 471 кг"
    ]
  },
  {
    id: "lwoop-four-sky",
    image: "img/lwoop-four-sky.png",
    brand: "LWOOP",
    model: "FOUR sky",
    price: 1361062,
    capacity: 4,
    soundproof: ">32 дБ",
    soundproofVal: 32,
    dimensions: "2300×1785×2364h",
    warranty: "7 лет",
    warrantyYears: 7,
    delivery: "50 раб. дней",
    furniture: "2 трёх-четырёхместных дивана, стол",
    power: "Силовая розетка + USB + USB-C",
    features: [
      "Сталь + авиационный алюминий",
      "Фетр 10 мм + акустическая ткань",
      "Мощная вентиляция 283 м³",
      "Триплекс 10 мм с ламинацией (опция)",
      "Мобильность, вес 750 кг"
    ]
  }
];

// Альтернативный прайс LWOOP с учётом рассрочки
const CABINS_LWOOP_INSTALLMENT = [
  { id: "lwoop-one-sky-i", image: "img/lwoop-one-sky.png", brand: "LWOOP+", model: "ONE sky (рассрочка)", basePrice: 708750, price: 737104, capacity: 1, warrantyYears: 7 },
  { id: "lwoop-onework-sky-i", image: "img/lwoop-onework-sky.png", brand: "LWOOP+", model: "ONE WORK sky (рассрочка)", basePrice: 834375, price: 876094, capacity: 1, warrantyYears: 7 },
  { id: "lwoop-double-sky-i", image: "img/lwoop-double-sky.png", brand: "LWOOP+", model: "DOUBLE sky (рассрочка)", basePrice: 1143178, price: 1212270, capacity: 2, warrantyYears: 7 },
  { id: "lwoop-four-sky-i", image: "img/lwoop-four-sky.png", brand: "LWOOP+", model: "FOUR sky (рассрочка)", basePrice: 1361062, price: 1424993, capacity: 4, warrantyYears: 7 }
];
